import { Component, OnInit } from "@angular/core";
import { HttpService } from "../utils/service/http.service";
import { get } from "lodash";

@Component({
  selector: "app-homepage",
  templateUrl: "./homepage.component.html",
  styleUrls: ["./homepage.component.css"]
})
export class HomepageComponent implements OnInit {
  products: any = [
    {
      id: 1,
      title: "i20 Magna",
      price: 570000,
      description: "Car for Sale",
      category: "Car",
      purchased_on: "23 Aug 2019",
      owner: 1,
      photos: [],
      thumbnail_url: "",
      thumbnail_uploaded: false,
      active: true,
      created_on: "2 Sep 2021",
      updated_on: null,
      expire_on: "2 Oct 2022",
      closed_on: null,
      location: { city: "Hisar", state: "Haryana" }
    },
    {
      id: 1,
      title: "i20 Magna",
      price: 570000,
      description: "Car for Sale",
      category: "Car",
      purchased_on: "23 Aug 2019",
      owner: 1,
      photos: [],
      thumbnail_url: "",
      thumbnail_uploaded: false,
      active: true,
      created_on: "2 Sep 2021",
      updated_on: null,
      expire_on: "2 Oct 2022",
      closed_on: null,
      location: { city: "Hisar", state: "Haryana" }
    },
    {
      id: 1,
      title: "i20 Magna",
      price: 570000,
      description: "Car for Sale",
      category: "Car",
      purchased_on: "23 Aug 2019",
      owner: 1,
      photos: [],
      thumbnail_url: "",
      thumbnail_uploaded: false,
      active: true,
      created_on: "2 Sep 2021",
      updated_on: null,
      expire_on: "2 Oct 2022",
      closed_on: null,
      location: { city: "Hisar", state: "Haryana" }
    },
    {
      id: 1,
      title: "i20 Magna",
      price: 570000,
      description: "Car for Sale",
      category: "Car",
      purchased_on: "23 Aug 2019",
      owner: 1,
      photos: [],
      thumbnail_url: "",
      thumbnail_uploaded: false,
      active: true,
      created_on: "2 Sep 2021",
      updated_on: null,
      expire_on: "2 Oct 2022",
      closed_on: null,
      location: { city: "Hisar", state: "Haryana" }
    },
    {
      id: 1,
      title: "i20 Magna",
      price: 570000,
      description: "Car for Sale",
      category: "Car",
      purchased_on: "23 Aug 2019",
      owner: 1,
      photos: [],
      thumbnail_url: "",
      thumbnail_uploaded: false,
      active: true,
      created_on: "2 Sep 2021",
      updated_on: null,
      expire_on: "2 Oct 2022",
      closed_on: null,
      location: { city: "Hisar", state: "Haryana" }
    },
    {
      id: 1,
      title: "i20 Magna",
      price: 570000,
      description: "Car for Sale",
      category: "Car",
      purchased_on: "23 Aug 2019",
      owner: 1,
      photos: [],
      thumbnail_url: "",
      thumbnail_uploaded: false,
      active: true,
      created_on: "2 Sep 2021",
      updated_on: null,
      expire_on: "2 Oct 2022",
      closed_on: null,
      location: { city: "Hisar", state: "Haryana" }
    },
    {
      id: 1,
      title: "i20 Magna",
      price: 570000,
      description: "Car for Sale",
      category: "Car",
      purchased_on: "23 Aug 2019",
      owner: 1,
      photos: [],
      thumbnail_url: "",
      thumbnail_uploaded: false,
      active: true,
      created_on: "2 Sep 2021",
      updated_on: null,
      expire_on: "2 Oct 2022",
      closed_on: null,
      location: { city: "Hisar", state: "Haryana" }
    },
    {
      id: 1,
      title: "i20 Magna",
      price: 570000,
      description: "Car for Sale",
      category: "Car",
      purchased_on: "23 Aug 2019",
      owner: 1,
      photos: [],
      thumbnail_url: "",
      thumbnail_uploaded: false,
      active: true,
      created_on: "2 Sep 2021",
      updated_on: null,
      expire_on: "2 Oct 2022",
      closed_on: null,
      location: { city: "Hisar", state: "Haryana" }
    },
    {
      id: 1,
      title: "i20 Magna",
      price: 570000,
      description: "Car for Sale",
      category: "Car",
      purchased_on: "23 Aug 2019",
      owner: 1,
      photos: [],
      thumbnail_url: "",
      thumbnail_uploaded: false,
      active: true,
      created_on: "2 Sep 2021",
      updated_on: null,
      expire_on: "2 Oct 2022",
      closed_on: null,
      location: { city: "Hisar", state: "Haryana" }
    },
    {
      id: 1,
      title: "i20 Magna",
      price: 570000,
      description: "Car for Sale",
      category: "Car",
      purchased_on: "23 Aug 2019",
      owner: 1,
      photos: [],
      thumbnail_url: "",
      thumbnail_uploaded: false,
      active: true,
      created_on: "2 Sep 2021",
      updated_on: null,
      expire_on: "2 Oct 2022",
      closed_on: null,
      location: { city: "Hisar", state: "Haryana" }
    },
    {
      id: 1,
      title: "i20 Magna",
      price: 570000,
      description: "Car for Sale",
      category: "Car",
      purchased_on: "23 Aug 2019",
      owner: 1,
      photos: [],
      thumbnail_url: "",
      thumbnail_uploaded: false,
      active: true,
      created_on: "2 Sep 2021",
      updated_on: null,
      expire_on: "2 Oct 2022",
      closed_on: null,
      location: { city: "Hisar", state: "Haryana" }
    },
    {
      id: 1,
      title: "i20 Magna",
      price: 570000,
      description: "Car for Sale",
      category: "Car",
      purchased_on: "23 Aug 2019",
      owner: 1,
      photos: [],
      thumbnail_url: "",
      thumbnail_uploaded: false,
      active: true,
      created_on: "2 Sep 2021",
      updated_on: null,
      expire_on: "2 Oct 2022",
      closed_on: null,
      location: { city: "Hisar", state: "Haryana" }
    },
    {
      id: 1,
      title: "i20 Magna",
      price: 570000,
      description: "Car for Sale",
      category: "Car",
      purchased_on: "23 Aug 2019",
      owner: 1,
      photos: [],
      thumbnail_url: "",
      thumbnail_uploaded: false,
      active: true,
      created_on: "2 Sep 2021",
      updated_on: null,
      expire_on: "2 Oct 2022",
      closed_on: null,
      location: { city: "Hisar", state: "Haryana" }
    },
    {
      id: 1,
      title: "i20 Magna",
      price: 570000,
      description: "Car for Sale",
      category: "Car",
      purchased_on: "23 Aug 2019",
      owner: 1,
      photos: [],
      thumbnail_url: "",
      thumbnail_uploaded: false,
      active: true,
      created_on: "2 Sep 2021",
      updated_on: null,
      expire_on: "2 Oct 2022",
      closed_on: null,
      location: { city: "Hisar", state: "Haryana" }
    },
    {
      id: 1,
      title: "i20 Magna",
      price: 570000,
      description: "Car for Sale",
      category: "Car",
      purchased_on: "23 Aug 2019",
      owner: 1,
      photos: [],
      thumbnail_url: "",
      thumbnail_uploaded: false,
      active: true,
      created_on: "2 Sep 2021",
      updated_on: null,
      expire_on: "2 Oct 2022",
      closed_on: null,
      location: { city: "Hisar", state: "Haryana" }
    },
    {
      id: 1,
      title: "i20 Magna",
      price: 570000,
      description: "Car for Sale",
      category: "Car",
      purchased_on: "23 Aug 2019",
      owner: 1,
      photos: [],
      thumbnail_url: "",
      thumbnail_uploaded: false,
      active: true,
      created_on: "2 Sep 2021",
      updated_on: null,
      expire_on: "2 Oct 2022",
      closed_on: null,
      location: { city: "Hisar", state: "Haryana" }
    },
    {
      id: 1,
      title: "i20 Magna",
      price: 570000,
      description: "Car for Sale",
      category: "Car",
      purchased_on: "23 Aug 2019",
      owner: 1,
      photos: [],
      thumbnail_url: "",
      thumbnail_uploaded: false,
      active: true,
      created_on: "2 Sep 2021",
      updated_on: null,
      expire_on: "2 Oct 2022",
      closed_on: null,
      location: { city: "Hisar", state: "Haryana" }
    },
    {
      id: 1,
      title: "i20 Magna",
      price: 570000,
      description: "Car for Sale",
      category: "Car",
      purchased_on: "23 Aug 2019",
      owner: 1,
      photos: [],
      thumbnail_url: "",
      thumbnail_uploaded: false,
      active: true,
      created_on: "2 Sep 2021",
      updated_on: null,
      expire_on: "2 Oct 2022",
      closed_on: null,
      location: { city: "Hisar", state: "Haryana" }
    },
    {
      id: 1,
      title: "i20 Magna",
      price: 570000,
      description: "Car for Sale",
      category: "Car",
      purchased_on: "23 Aug 2019",
      owner: 1,
      photos: [],
      thumbnail_url: "",
      thumbnail_uploaded: false,
      active: true,
      created_on: "2 Sep 2021",
      updated_on: null,
      expire_on: "2 Oct 2022",
      closed_on: null,
      location: { city: "Hisar", state: "Haryana" }
    },
    {
      id: 1,
      title: "i20 Magna",
      price: 570000,
      description: "Car for Sale",
      category: "Car",
      purchased_on: "23 Aug 2019",
      owner: 1,
      photos: [],
      thumbnail_url: "",
      thumbnail_uploaded: false,
      active: true,
      created_on: "2 Sep 2021",
      updated_on: null,
      expire_on: "2 Oct 2022",
      closed_on: null,
      location: { city: "Hisar", state: "Haryana" }
    },
    {
      id: 1,
      title: "i20 Magna",
      price: 570000,
      description: "Car for Sale",
      category: "Car",
      purchased_on: "23 Aug 2019",
      owner: 1,
      photos: [],
      thumbnail_url: "",
      thumbnail_uploaded: false,
      active: true,
      created_on: "2 Sep 2021",
      updated_on: null,
      expire_on: "2 Oct 2022",
      closed_on: null,
      location: { city: "Hisar", state: "Haryana" }
    },
    {
      id: 1,
      title: "i20 Magna",
      price: 570000,
      description: "Car for Sale",
      category: "Car",
      purchased_on: "23 Aug 2019",
      owner: 1,
      photos: [],
      thumbnail_url: "",
      thumbnail_uploaded: false,
      active: true,
      created_on: "2 Sep 2021",
      updated_on: null,
      expire_on: "2 Oct 2022",
      closed_on: null,
      location: { city: "Hisar", state: "Haryana" }
    },
    {
      id: 1,
      title: "i20 Magna",
      price: 570000,
      description: "Car for Sale",
      category: "Car",
      purchased_on: "23 Aug 2019",
      owner: 1,
      photos: [],
      thumbnail_url: "",
      thumbnail_uploaded: false,
      active: true,
      created_on: "2 Sep 2021",
      updated_on: null,
      expire_on: "2 Oct 2022",
      closed_on: null,
      location: { city: "Hisar", state: "Haryana" }
    },
    {
      id: 1,
      title: "i20 Magna",
      price: 570000,
      description: "Car for Sale",
      category: "Car",
      purchased_on: "23 Aug 2019",
      owner: 1,
      photos: [],
      thumbnail_url: "",
      thumbnail_uploaded: false,
      active: true,
      created_on: "2 Sep 2021",
      updated_on: null,
      expire_on: "2 Oct 2022",
      closed_on: null,
      location: { city: "Hisar", state: "Haryana" }
    },
    {
      id: 1,
      title: "i20 Magna",
      price: 570000,
      description: "Car for Sale",
      category: "Car",
      purchased_on: "23 Aug 2019",
      owner: 1,
      photos: [],
      thumbnail_url: "",
      thumbnail_uploaded: false,
      active: true,
      created_on: "2 Sep 2021",
      updated_on: null,
      expire_on: "2 Oct 2022",
      closed_on: null,
      location: { city: "Hisar", state: "Haryana" }
    },
    {
      id: 1,
      title: "i20 Magna",
      price: 570000,
      description: "Car for Sale",
      category: "Car",
      purchased_on: "23 Aug 2019",
      owner: 1,
      photos: [],
      thumbnail_url: "",
      thumbnail_uploaded: false,
      active: true,
      created_on: "2 Sep 2021",
      updated_on: null,
      expire_on: "2 Oct 2022",
      closed_on: null,
      location: { city: "Hisar", state: "Haryana" }
    }
  ];

  constructor(private httpService: HttpService) {}

  ngOnInit() {
    console.log('homepage')
    // this.httpService.getRequest(`products/allProduct`).subscribe(
    //   res => {
    //     this.products = get(res, "result");
    //   },
    //   err => {
    //     console.log("error", "", "Something went wrong");
    //   }
    // );
  }
}
